/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumLink: typeof import('./components/artist/AlbumLink.vue')['default']
    ArtistsCover: typeof import('./components/cover/ArtistsCover.vue')['default']
    ArtistsLink: typeof import('./components/artist/ArtistsLink.vue')['default']
    BackBtn: typeof import('./components/button/BackBtn.vue')['default']
    BackToTop: typeof import('./components/button/BackToTop.vue')['default']
    CardRow: typeof import('./components/layout/CardRow.vue')['default']
    Col: typeof import('./components/layout/Col.vue')['default']
    CommonCard: typeof import('./components/CommonCard.vue')['default']
    Control: typeof import('./components/Control.vue')['default']
    ControlCenterToggle: typeof import('./components/toggle/ControlCenterToggle.vue')['default']
    Cover: typeof import('./components/cover/Cover.vue')['default']
    DiscoverLoader: typeof import('./components/skeleton/DiscoverLoader.vue')['default']
    DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
    ExploreLoader: typeof import('./components/skeleton/ExploreLoader.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    Item: typeof import('./components/list/Item.vue')['default']
    List: typeof import('./components/list/List.vue')['default']
    ListLoader: typeof import('./components/skeleton/ListLoader.vue')['default']
    ListSkeleton: typeof import('./components/skeleton/ListSkeleton.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    MinimalBtn: typeof import('./components/button/MinimalBtn.vue')['default']
    MusicLoader: typeof import('./components/skeleton/MusicLoader.vue')['default']
    ReloadBtn: typeof import('./components/button/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/toggle/SearchInput.vue')['default']
    SearchToggle: typeof import('./components/toggle/SearchToggle.vue')['default']
    Select: typeof import('./components/menu/Select.vue')['default']
    SwitchCard: typeof import('./components/SwitchCard.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
    ThemeToggle: typeof import('./components/toggle/ThemeToggle.vue')['default']
    ThumbLikeToggle: typeof import('./components/toggle/ThumbLikeToggle.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    VSquareBtn: typeof import('./components/button/VSquareBtn.vue')['default']
  }
}

// For TSX support
declare global {
  const AlbumLink: typeof import('./components/artist/AlbumLink.vue')['default']
  const ArtistsCover: typeof import('./components/cover/ArtistsCover.vue')['default']
  const ArtistsLink: typeof import('./components/artist/ArtistsLink.vue')['default']
  const BackBtn: typeof import('./components/button/BackBtn.vue')['default']
  const BackToTop: typeof import('./components/button/BackToTop.vue')['default']
  const CardRow: typeof import('./components/layout/CardRow.vue')['default']
  const Col: typeof import('./components/layout/Col.vue')['default']
  const CommonCard: typeof import('./components/CommonCard.vue')['default']
  const Control: typeof import('./components/Control.vue')['default']
  const ControlCenterToggle: typeof import('./components/toggle/ControlCenterToggle.vue')['default']
  const Cover: typeof import('./components/cover/Cover.vue')['default']
  const DiscoverLoader: typeof import('./components/skeleton/DiscoverLoader.vue')['default']
  const DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
  const ExploreLoader: typeof import('./components/skeleton/ExploreLoader.vue')['default']
  const Headline: typeof import('./components/Headline.vue')['default']
  const Item: typeof import('./components/list/Item.vue')['default']
  const List: typeof import('./components/list/List.vue')['default']
  const ListLoader: typeof import('./components/skeleton/ListLoader.vue')['default']
  const ListSkeleton: typeof import('./components/skeleton/ListSkeleton.vue')['default']
  const Menu: typeof import('./components/menu/Menu.vue')['default']
  const MinimalBtn: typeof import('./components/button/MinimalBtn.vue')['default']
  const MusicLoader: typeof import('./components/skeleton/MusicLoader.vue')['default']
  const ReloadBtn: typeof import('./components/button/ReloadBtn.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchInput: typeof import('./components/toggle/SearchInput.vue')['default']
  const SearchToggle: typeof import('./components/toggle/SearchToggle.vue')['default']
  const Select: typeof import('./components/menu/Select.vue')['default']
  const SwitchCard: typeof import('./components/SwitchCard.vue')['default']
  const Tag: typeof import('./components/Tag.vue')['default']
  const ThemeToggle: typeof import('./components/toggle/ThemeToggle.vue')['default']
  const ThumbLikeToggle: typeof import('./components/toggle/ThumbLikeToggle.vue')['default']
  const Title: typeof import('./components/Title.vue')['default']
  const VSquareBtn: typeof import('./components/button/VSquareBtn.vue')['default']
}