/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalSearch: typeof import('./components/GlobalSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkspaceInit: typeof import('./components/WorkspaceInit.vue')['default']
  }
}

// For TSX support
declare global {
  const GlobalSearch: typeof import('./components/GlobalSearch.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WorkspaceInit: typeof import('./components/WorkspaceInit.vue')['default']
}