/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardRow: typeof import('./components/layout/CardRow.vue')['default']
    DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
    GlobalSearch: typeof import('./components/GlobalSearch.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./components/Title.vue')['default']
    WorkspaceInit: typeof import('./components/WorkspaceInit.vue')['default']
  }
}

// For TSX support
declare global {
  const CardRow: typeof import('./components/layout/CardRow.vue')['default']
  const DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
  const GlobalSearch: typeof import('./components/GlobalSearch.vue')['default']
  const Headline: typeof import('./components/Headline.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Title: typeof import('./components/Title.vue')['default']
  const WorkspaceInit: typeof import('./components/WorkspaceInit.vue')['default']
}